### ISSUE TITLE
Timeout for request

### ISSUE THREAD

**Issue by weejulius** [laforge49/JActor#38]
Hi,

Looks to me we could be able to reject request after timeout?

Thanks

Julius

**Comment by weejulius** [comment]
Hi,

Sorry for one more question, I saw an article saying that the performance of jactor in 4.0 is 10 times slower than before? is it true, or it is fixed?

Thanks
Jjulius

**Comment by laforge49** [comment]
Speed used to exceed 1billion mps when the same mailbox was used, but exceptions were not being handled. It slowed down and then after a month's work I got it going a bit faster.

Currently we are exceeding 200 million mps on my test environment. I have since thought of ways to get more performance, but it is not my highest priority right now. On the flip side, it seems to work nicely on a lot of odd cases that were not previously unit tested. (Some of the latest tests are part of the JASocket project, which uses a lot of events.)

As for rejects and timeouts, all responses to a request after the first response are ignored. And an exception for this purpose is considered a response. So if you throw an exception on timeout then either the exception of the response will be ignored, if both occur, depending on which occurred first.
