### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by menacher** [laforge49/JActor#4]
There is no link to examples using this library in the main page. Wiki with some code samples would be very helpful.

**Comment by laforge49** [comment]
A good idea.

But give me a week or so. Right now I'm in the middle of reworking the code
for JActor 2.

Bill

On Sun, Feb 5, 2012 at 1:37 AM, Abraham Menacherry <
reply@reply.github.com

**Comment by laforge49** [comment]
Menacher,

Here's the first installment on my promise: https://github.com/laforge49/JActor/wiki/Synchronous-Programming

The focus of this first document is on the new features of JActor 2.

Bill

**Comment by menacher** [comment]
Bill,

This is good stuff! Let me start off then...

**Comment by laforge49** [comment]
Just to make sure the problem isn't with the jactor.events package, I wrote QuadTest which has 4 threads sending to a single JAEventQueue. Works great as expected, though I never tested JAEventQueue with multiple writers before. :-O

So I'm pretty sure the problem is at a higher level, where one mailbox takes control of another. Which works fine for 1 or 2 threads, but not so fine with 3 threads contending for control of the same mailbox. 

So I've done enough dancing around the problem. Time perhaps to review the code in depth.

**Comment by laforge49** [comment]
Here is the second installment on my promise: https://github.com/laforge49/JActor/wiki/Multithreading

I was delighted to find a number of bugs while working on this, which is why the current release is 2.0.0 RC3!

**Comment by laforge49** [comment]
Here's the third installment: https://github.com/laforge49/JActor/wiki/Initialization

**Comment by laforge49** [comment]
Fourth installment: https://github.com/laforge49/JActor/wiki/Concurrency

**Comment by menacher** [comment]
Closing the issue. Thanks!
